### ISSUE TITLE
Not working with Oculus

### ISSUE THREAD

**Issue by wickles** [mdovgialo/steam-vr-wheel#11]
I'm running 2.5.2 with Oculus Rift+Touch. It shows up in SteamVR dashboard and seems to work fine there. But when I launch any game the wheel disappears and the vJoy controller no longer registers any input. Then when I quit back to SteamVR dashboard it comes back and works again. Launch a game, stops working, repeat. 

It also made my Xbox One controller stop working or even registering in SteamVR and Oculus. But it still shows up in USB Game Controllers and registers input there. Maybe that's just vJoy though.

Any tips?

**Comment by mdovgialo** [comment]
It will work with any game working through SteamVR/OpenVR API. If the game uses Oculus API - it might close all SteamVR apps. I don't have Oculus, so I can't really test and develop version for Oculus API...

**Comment by wickles** [comment]
I meant to mention that I tried to run Project Cars in Vive/SteamVR mode and it still didn't work.

**Comment by mdovgialo** [comment]
Try this version.

https://github.com/mdovgialo/steam-vr-wheel/releases/tag/2.3.8a

I haven't used my pp in while, maybe one of the SteamVR updates broke something...
