### ISSUE TITLE
Input Not Registering While In-Game On WMR

### ISSUE THREAD

**Issue by ghost** [mdovgialo/steam-vr-wheel#12]
I'm running on version 2.5.2 with a dell visor. When in the steam dashboard and house, my input workes fine and displays in the config menu. However, as soon as I get into a game, it stops working. If I move my mouse from the game window, it starts working again. I move it back, it stops working. Could this have something to do with steamvr taking ownership of the device?
Edit: The movements and events are still appearing in the debug mode.

**Comment by mdovgialo** [comment]
Ok, I've double checked on my Vive. I haven't used it for a while but looks like no update broke it - I tried DirtRally through ReVive.

I don't have a dell visor.  But I might be able to fix it, what game is it? Are any other controllers connected? What API game uses, SteamVR, WMR? If events are still appearing in the debug mode then then it should work, I'm not sure what could be wrong if it doesn't. I would need the game to experiment with.

**Comment by wjdaggett** [comment]
Could it be related to the new steamvr input remapping that came with the
last steamvr beta release?

**Comment by ghost** [comment]
It is in Elite Dangerous with SteamVR API. They are the only other controllers connected.

**Comment by mdovgialo** [comment]
¯\_(ツ)_/¯
