### ISSUE TITLE
Double joystick mode aren't grabbable

### ISSUE THREAD

**Issue by anselme16** [mdovgialo/steam-vr-wheel#13]
Everything is in the title,

it would be nice if the "grabbable joystick" option worked with the double joystick mode.

Or maybe make a grabbable joystick + throttle mode. ( i was planning to use one of the second joystick axis for throttle )

**Comment by mdovgialo** [comment]
In single joystick mode there is a grabbable joystick and grabbable throttle.

When you press and hold left grip button moving controller back/forth, up/down or twisting it changes one of 3 "throttle" axes

**Comment by mdovgialo** [comment]
and
