### ISSUE TITLE
Oculus trigger axis stay at 0

### ISSUE THREAD

**Issue by mdovgialo** [mdovgialo/steam-vr-wheel#15]

**Comment by F0gboy** [comment]
When i run debug i get errors and no axis are moving

**Comment by mdovgialo** [comment]
What kind of errors?

**Comment by F0gboy** [comment]
C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist>python.exe open-vr-wheel.py DEBUG
Traceback (most recent call last):
  File "open-vr-wheel.py", line 6, in <module>
    steam_vr_wheel.wheel.main()
  File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\steam_vr_wheel\wheel.py", line 93, in main
    openvr.init(openvr.VRApplication_Background)
  File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr\__init__.py", line 4964, in init
    initInternal(applicationType)
  File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr\__init__.py", line 5068, in initInternal
    _checkInitError(error.value)
  File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr\__init__.py", line 4950, in _checkInitError
    raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
openvr.OpenVRError: b'VRInitError_Init_NoServerForBackgroundApp' (error number 121)

**Comment by mdovgialo** [comment]
> C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist>python.exe open-vr-wheel.py DEBUG
> Traceback (most recent call last):
> File "open-vr-wheel.py", line 6, in 
> steam_vr_wheel.wheel.main()
> File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\steam_vr_wheel\wheel.py", line 93, in main
> openvr.init(openvr.VRApplication_Background)
> File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr__init__.py", line 4964, in init
> initInternal(applicationType)
> File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr__init__.py", line 5068, in initInternal
> _checkInitError(error.value) File "C:\Users\Jasper\Desktop\steam-vr-wheel-oculus-fix-legacy\steam_vr_wheel_dist\openvr__init__.py", line 4950, in _checkInitError
> raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
> openvr.OpenVRError: b'VRInitError_Init_NoServerForBackgroundApp' (error number 121)

You have to run Steam-VR before launching steam vr wheel. In the error it says that it didnt find openvr/steam vr server running.

**Comment by mdovgialo** [comment]
¯\_(ツ)_/¯
