### ISSUE TITLE
Problem with buttons VJOY

### ISSUE THREAD

**Issue by Marlon90** [mdovgialo/steam-vr-wheel#16]
Hello, your application is the only one which exists at the moment to emulate an joystick with VR Controllers. It is realy good because the range of it is relative. It can be compared to a joystick having a long extension on it. The problem is that vjoy is not recognizing any buttons, just axis and even if in windows it shows input for buttons it does not in games (tested with War Thunder). It would be good if you can fix this. Used a Rift S with its touch controllers.

**Comment by mdovgialo** [comment]
I don't have Rift to test, and I'had reports for some people it working and not. The non working part is also quite random - which part is not working (for some triggers, for some buttons). I actually have no idea why. I think part of problem is which SDK the game is using. My app was designed and tested using OpenVR/SteamVR SDK and games, if a game runs in Oculus SDK mode - I have no idea what happens with my app.

If USB Game Controllers window  shows  button activations - it should work. If you open SteamVR overlay - buttons won't be registered though. I played WarThunder long time ago with a Vive and it had no problems.

Silly question but have you gone through game input configuration? Maybe the game assumes wrong default buttons for expected actions?

**Comment by Marlon90** [comment]
Hello. With input configuration you mean the controls in War Thunder, right? Yes, I checked that. It appears to me that it works USB Game Controller Panel (Windows) as long as I don't have a game started. To be honest I just checked War Thunder so far (tested the normal version and Steam version). I've no idea why it is not recognizing it because it does not make sense. If USB Joystick Panel can see button inputs it should not disappear randomly. It also surprises me that your application - which was also hard to find for me - is the one and only which emulates a virtual joystick in VR. I original searched for a virtual joystick you had to grab with the touch controllers and then the input is sent to the game you play but then I found your app instead.
I am experienced in 3D Modelling (Hard surface). If you still develop this application and want some help with 3D Models I can give you a hand. Also I can test it for RIFT-S Touch Controller. I got the basics of programming but it is not my passion.

**Comment by mdovgialo** [comment]
You could also try this one:
https://github.com/dantman/elite-vr-cockpit

Does WarThunder runs in Oculus mode? That could be a problem, or maybe you have some kind of overlay running?

I was gonna update it a bit for Index controllers, but it requires a substantial rewrite to Steam VR Input  2.0 which would allow the app to be more configurable, but, I'm on vocation for a few weeks, away from VR, and later will be quite busy with my job, so I don't know when I could debug something...

**Comment by Marlon90** [comment]
Okay I see. 
The elite-vr-cockpit is for elite dangerous. It has not worked with war thunder so far.
