### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by browhattheheck1** [mdovgialo/steam-vr-wheel#19]
Wheel is in the right position, I can move it by grabbing it. So i booted up project cars 2 and it doesn't move the wheel in game or anything

**Comment by mdovgialo** [comment]
Does it work in USB Game controllers? @snikabarz

**Comment by umbertomarotta** [comment]
Same problem here with PC2. It works in USB Game controllers for me, but not in game. Oddly enough, the triggers work properly.

**Comment by mdovgialo** [comment]
Seems like you need to setup controls - select controller type and wheel axis somewhere in the game settings. I don't have PC2 so I can't really help you with that.

**Comment by umbertomarotta** [comment]
Just found out that if you set "Custom Controller" instead of "Custom Wheel" it works, but still sucks because I had to set FULLTURN around 0.65 to get a 1:1 (delayed) movement. Seems PC2 has a bad history with unsupported controllers.

**Comment by mdovgialo** [comment]
I guess it treats it as a controller instead of a wheel, applying some smoothing or something, sadly I have no idea what PC2 might want. My software just imitates generic USB game controller.
