### ISSUE TITLE
Pauses immediately after starting up

### ISSUE THREAD

**Issue by Nomagno** [mdovgialo/steam-vr-wheel#22]
I get this when running the bat file, and have installed everything it asked for the release version (and the developer one, just to make sure)
```
C:\Users\User\Downloads\steam-vr-wheel-2.5.4\steam-vr-wheel-2.5.4>cd steam_vr_wheel_dist

C:\Users\User\Downloads\steam-vr-wheel-2.5.4\steam-vr-wheel-2.5.4\steam_vr_wheel_dist>python.exe open-vr-wheel.py

C:\Users\User\Downloads\steam-vr-wheel-2.5.4\steam-vr-wheel-2.5.4\steam_vr_wheel_dist>pause
Press any key to continue . . .
```
This results in uh, well, *absolutely nothing* happening in SteamVR...

**Comment by mdovgialo** [comment]
Just to make sure, you've downloaded this zip https://github.com/mdovgialo/steam-vr-wheel/releases/download/2.5.4/steam-vr-wheel-2.5.4.zip and double clicked the `steam-vr-wheel.bat` ?

I know it might be a dumb question, but. Did you unpack the zip properly? If yes, it seems you have something overloading/blocking my version of python running. Maybe you have antivirus blocking unknown exe files?

**Comment by mdovgialo** [comment]
You can try going to that steam_vr_wheel_dist folder, and make a screenshot?
It should be like this:
![image](https://user-images.githubusercontent.com/6193380/89355662-3e8f5d00-d6bc-11ea-92c0-e93a99be2e68.png)

you can try dragging `open-vr-wheel.py` file unto `python.exe` file, it should run that way too. Another idea, it will not run on 32 bit windows, but most likely you wouldn't be able to run VR on 32 bits anyway, I think.

**Comment by Nomagno** [comment]
Well that was quick, thanks for the assistance. It was just WinRar being dumb and not extracting all the files.
Time to play DCS world! I'll dedicate you a barrel roll :)
