### ISSUE TITLE
ProjectCars2 does not detect steering input

### ISSUE THREAD

**Issue by Abadulrehman** [mdovgialo/steam-vr-wheel#24]
I've tried to setup the wheel using the "custom wheel" setting in Project Cars 2, but it simply does not want to work. First, there is trouble registering the input, and then, even if it does detect the input from the wheel and assigns it to Vjoy X axis, it refuses to actually work in-game.

**Comment by mdovgialo** [comment]
Sorry, I don't have project cars. It works as generic USB wheel.  I can only advise by searching how to setup any generic DirectX wheel with PC2.
