### ISSUE TITLE
Thumbsticks not mapped for Windows Mixed Reality Motion Controllers

### ISSUE THREAD

**Issue by wjdaggett** [mdovgialo/steam-vr-wheel#9]
Hey, I commented on your youtube video showing off the VR joystick about adding support for the WMR controllers. I've attached a picture of the debug using the double joystick script 
![capture](https://user-images.githubusercontent.com/7856403/37003799-481bccc4-209c-11e8-9d8e-fb0da6347c1a.PNG) looks like the sticks are showing up as Axis 2 and go from ~0 to ~1/-1 at the extremes for the X and Y.

If you need more information just let me know!

Thanks again for looking into this.

**Comment by mdovgialo** [comment]
Sorry for not looking into it for so long. I might have some time for it this weekend. I'm thinking of bigger redesign, to allow configure of any function to any key. But in meantime you could tell me the preferable axis for the WMR joysticks.

**Comment by wjdaggett** [comment]
No problem at all! Thanks for taking time to work on this. So I guess I was wondering if they could be mapped to act as a hatswitch instead of a joystick? Example being like position ~0:~1 could equal button 20 in vJoy or something along those lines.

**Comment by wjdaggett** [comment]
Hey mdovgialo, was wondering if you had gotten a chance to take a look at this. No big deal if you haven't just wondering 😁

**Comment by mdovgialo** [comment]
¯\_(ツ)_/¯
